import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import "../CSS/AccountSettings.css";
import HeaderText from "../Components/HeaderText";
import NewAgeHeader from "../Components/NewAgeHeader";
import Footer from "../Components/Footer";
import { useCart } from "../Context/CartContext";

const defaultImage = "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400";
const readUser = () => { try { const saved = localStorage.getItem("user"); return saved && saved !== "undefined" ? JSON.parse(saved) : {}; } catch { return {}; } };

const AccountSettings = () => {
  const navigate = useNavigate(); const { clearCart } = useCart(); const inputRef = useRef(null); const storedUser = readUser();
  const [form, setForm] = useState({ firstName: storedUser.firstName || storedUser.name?.split(" ")[0] || "", lastName: storedUser.lastName || storedUser.name?.split(" ").slice(1).join(" ") || "", email: storedUser.email || "", phone: storedUser.phone || "", gender: storedUser.gender || "" });
  const [image, setImage] = useState(storedUser.profileImage || defaultImage); const [message, setMessage] = useState("");
  const updateField = (e) => setForm((current) => ({ ...current, [e.target.name]: e.target.value }));
  const handleImage = (e) => { const file = e.target.files?.[0]; if (!file) return; if (!/image\/(png|jpeg|gif)/.test(file.type) || file.size > 10 * 1024 * 1024) { setMessage("Choose a PNG, JPEG, or GIF smaller than 10MB."); e.target.value = ""; return; } const reader = new FileReader(); reader.onload = () => { setImage(reader.result); setMessage("Image ready to save."); }; reader.readAsDataURL(file); };
  const handleSave = (e) => { e.preventDefault(); localStorage.setItem("user", JSON.stringify({ ...storedUser, ...form, name: `${form.firstName} ${form.lastName}`.trim(), profileImage: image })); setMessage("Your profile has been saved."); };
  const handleRemoveImage = () => { setImage(defaultImage); if (inputRef.current) inputRef.current.value = ""; setMessage("Profile image removed. Save changes to keep this update."); };
  const handleLogout = () => { clearCart(); localStorage.removeItem("token"); localStorage.removeItem("user"); navigate("/"); };
  const handleDelete = () => { if (!window.confirm("Delete your account and locally saved profile data? This cannot be undone.")) return; clearCart(); localStorage.removeItem("token"); localStorage.removeItem("user"); navigate("/"); };
  return <div className="account-page"><HeaderText /><NewAgeHeader /><main className="account-holder"><div className="account-container"><div className="title-section"><h1>Account Settings</h1><p>Edit your name, picture, and contact details.</p></div><div className="profile-section"><img src={image} alt="Your profile" className="profile-image" /><div className="profile-details"><h2>Profile</h2><div className="profile-buttons"><button className="upload-btn" type="button" onClick={() => inputRef.current?.click()}>Upload Image</button><button className="remove-btn" type="button" onClick={handleRemoveImage}>Remove</button><input ref={inputRef} className="profile-file-input" type="file" accept="image/png,image/jpeg,image/gif" onChange={handleImage} /></div><p className="support-text">We support PNGs, JPEGs and GIFs under 10MB.</p></div></div><form className="settings-form" onSubmit={handleSave}><section className="settings-right"><div className="group-form"><label htmlFor="firstName">First Name</label><input id="firstName" name="firstName" value={form.firstName} onChange={updateField} placeholder="Enter your name" required /></div><div className="group-form"><label htmlFor="email">Email</label><input id="email" name="email" type="email" value={form.email} onChange={updateField} placeholder="Enter your email" required /></div><div className="group-form"><label htmlFor="gender">Gender</label><select id="gender" name="gender" value={form.gender} onChange={updateField}><option value="">Select option</option><option>Female</option><option>Male</option><option>Prefer not to say</option></select></div><div className="action-buttons"><button className="save-btn" type="submit">Save Changes</button><button className="delete-btn" type="button" onClick={handleDelete}>Delete Account</button></div></section><section className="settings-left"><div className="group-form"><label htmlFor="lastName">Last Name</label><input id="lastName" name="lastName" value={form.lastName} onChange={updateField} placeholder="Enter last name" /></div><div className="group-form"><label htmlFor="phone">Phone Number</label><input id="phone" name="phone" value={form.phone} onChange={updateField} placeholder="Input phone number" inputMode="tel" /></div></section></form>{message && <p className="account-message" role="status">{message}</p>}<button className="logout-btn" type="button" onClick={handleLogout}>Logout</button></div></main><Footer /></div>;
};
export default AccountSettings;
